#!/usr/bin/env bash
# Burn word captions + mix SFX onto the host's memes/VO export, single encode pass.
# Usage: bash scratch/build-chromebball-sfx.sh [tiktok|youtube|both]
#   tiktok  - red hook banner baked 0-1.5s (fades over the last 0.25s)
#   youtube - no baked hook; the hook is the separate uploaded thumbnail instead
# GENERATED by scratch/gen-chromebball-sfx.mjs — edit that, not this.
# 8 swooshes (pack changes) | 17 cha-chings (comp pops) | 1 cost sting @ 12.9s | recap silent
set -u
cd "$(dirname "$0")/.." || exit 1
MODE="${1:-both}"
if [ "$MODE" = "tiktok" ] || [ "$MODE" = "both" ]; then
  echo "=== tiktok (hook baked) ==="
    ffmpeg -y -hide_banner -i "cards/sources/chromebball/ChromeBballneedcaption.mp4" \
  -loop 1 -framerate 60 -t 1.70 -i "scratch/overlay-preview/chromebball_hook_tiktok.png" \
      -i "cards/sounds/cardswap.m4a" \
      -i "cards/sounds/cardmoneysound.m4a" \
      -i "cards/sounds/packcostsound.m4a" \
      -filter_complex "[1:v]format=rgba,fade=t=out:st=1.25:d=0.25:alpha=1[hook];
      [0:v][hook]overlay=0:0:enable='between(t,0,1.5)'[vhook];
      [vhook]subtitles=scratch/chromebball-captions.ass[vout];
      [2:a]aformat=sample_rates=48000:channel_layouts=stereo,volume=3.716338758988338,asplit=8[sw0][sw1][sw2][sw3][sw4][sw5][sw6][sw7];
      [sw0]adelay=delays=11230:all=1[swd0];
      [sw1]adelay=delays=19700:all=1[swd1];
      [sw2]adelay=delays=32830:all=1[swd2];
      [sw3]adelay=delays=43650:all=1[swd3];
      [sw4]adelay=delays=52600:all=1[swd4];
      [sw5]adelay=delays=63800:all=1[swd5];
      [sw6]adelay=delays=73500:all=1[swd6];
      [sw7]adelay=delays=94200:all=1[swd7];
      [3:a]aformat=sample_rates=48000:channel_layouts=stereo,volume=9.331859124862058,asplit=17[ch0][ch1][ch2][ch3][ch4][ch5][ch6][ch7][ch8][ch9][ch10][ch11][ch12][ch13][ch14][ch15][ch16];
      [ch0]adelay=delays=13070:all=1[chd0];
      [ch1]adelay=delays=16870:all=1[chd1];
      [ch2]adelay=delays=21370:all=1[chd2];
      [ch3]adelay=delays=25070:all=1[chd3];
      [ch4]adelay=delays=37520:all=1[chd4];
      [ch5]adelay=delays=44070:all=1[chd5];
      [ch6]adelay=delays=48220:all=1[chd6];
      [ch7]adelay=delays=50520:all=1[chd7];
      [ch8]adelay=delays=55120:all=1[chd8];
      [ch9]adelay=delays=58320:all=1[chd9];
      [ch10]adelay=delays=60320:all=1[chd10];
      [ch11]adelay=delays=65370:all=1[chd11];
      [ch12]adelay=delays=81720:all=1[chd12];
      [ch13]adelay=delays=90020:all=1[chd13];
      [ch14]adelay=delays=95970:all=1[chd14];
      [ch15]adelay=delays=98020:all=1[chd15];
      [ch16]adelay=delays=100820:all=1[chd16];
      [4:a]aformat=sample_rates=48000:channel_layouts=stereo,volume=1.495368906418058,asplit=1[st0];
      [st0]adelay=delays=12900:all=1[std0];
      [0:a][swd0][swd1][swd2][swd3][swd4][swd5][swd6][swd7][chd0][chd1][chd2][chd3][chd4][chd5][chd6][chd7][chd8][chd9][chd10][chd11][chd12][chd13][chd14][chd15][chd16][std0]amix=inputs=27:normalize=0:duration=first,alimiter=limit=0.95[aout]" \
      -map "[vout]" -map "[aout]" -t 110.99 \
      -c:v hevc_nvenc -preset p5 -rc vbr -cq 19 -b:v 0 -tag:v hvc1 -c:a aac -b:a 256k \
      "cards/renders/chromebball_final_tiktok.mp4"
fi
if [ "$MODE" = "youtube" ] || [ "$MODE" = "both" ]; then
  echo "=== youtube (no baked hook) ==="
    ffmpeg -y -hide_banner -i "cards/sources/chromebball/ChromeBballneedcaption.mp4" \
      -i "cards/sounds/cardswap.m4a" \
      -i "cards/sounds/cardmoneysound.m4a" \
      -i "cards/sounds/packcostsound.m4a" \
      -filter_complex "[0:v]subtitles=scratch/chromebball-captions.ass[vout];
      [1:a]aformat=sample_rates=48000:channel_layouts=stereo,volume=3.716338758988338,asplit=8[sw0][sw1][sw2][sw3][sw4][sw5][sw6][sw7];
      [sw0]adelay=delays=11230:all=1[swd0];
      [sw1]adelay=delays=19700:all=1[swd1];
      [sw2]adelay=delays=32830:all=1[swd2];
      [sw3]adelay=delays=43650:all=1[swd3];
      [sw4]adelay=delays=52600:all=1[swd4];
      [sw5]adelay=delays=63800:all=1[swd5];
      [sw6]adelay=delays=73500:all=1[swd6];
      [sw7]adelay=delays=94200:all=1[swd7];
      [2:a]aformat=sample_rates=48000:channel_layouts=stereo,volume=9.331859124862058,asplit=17[ch0][ch1][ch2][ch3][ch4][ch5][ch6][ch7][ch8][ch9][ch10][ch11][ch12][ch13][ch14][ch15][ch16];
      [ch0]adelay=delays=13070:all=1[chd0];
      [ch1]adelay=delays=16870:all=1[chd1];
      [ch2]adelay=delays=21370:all=1[chd2];
      [ch3]adelay=delays=25070:all=1[chd3];
      [ch4]adelay=delays=37520:all=1[chd4];
      [ch5]adelay=delays=44070:all=1[chd5];
      [ch6]adelay=delays=48220:all=1[chd6];
      [ch7]adelay=delays=50520:all=1[chd7];
      [ch8]adelay=delays=55120:all=1[chd8];
      [ch9]adelay=delays=58320:all=1[chd9];
      [ch10]adelay=delays=60320:all=1[chd10];
      [ch11]adelay=delays=65370:all=1[chd11];
      [ch12]adelay=delays=81720:all=1[chd12];
      [ch13]adelay=delays=90020:all=1[chd13];
      [ch14]adelay=delays=95970:all=1[chd14];
      [ch15]adelay=delays=98020:all=1[chd15];
      [ch16]adelay=delays=100820:all=1[chd16];
      [3:a]aformat=sample_rates=48000:channel_layouts=stereo,volume=1.495368906418058,asplit=1[st0];
      [st0]adelay=delays=12900:all=1[std0];
      [0:a][swd0][swd1][swd2][swd3][swd4][swd5][swd6][swd7][chd0][chd1][chd2][chd3][chd4][chd5][chd6][chd7][chd8][chd9][chd10][chd11][chd12][chd13][chd14][chd15][chd16][std0]amix=inputs=27:normalize=0:duration=first,alimiter=limit=0.95[aout]" \
      -map "[vout]" -map "[aout]" -t 110.99 \
      -c:v hevc_nvenc -preset p5 -rc vbr -cq 19 -b:v 0 -tag:v hvc1 -c:a aac -b:a 256k \
      "cards/renders/chromebball_final_youtube.mp4"
fi
