#!/usr/bin/env bash
# Composite the chromebball overlay elements onto the host's pre-cut.
# Usage: bash scratch/run-chromebball-composite.sh [test|review|final]
#   test   - first 30s at 4K, to eyeball chip placement fast
#   review - full length at 1080p h264, for timing review
#   final  - full length native 2160x3840 hevc, the deliverable
# GENERATED by scratch/gen-chromebball-composite.mjs — edit that, not this.
set -u
cd "$(dirname "$0")/.." || exit 1
MODE="${1:-review}"
case "$MODE" in
  test)
    ffmpeg -y -hide_banner -i "cards/sources/chromebball/ChromeBBall2425.mp4" \
      -itsoffset 12.9 -i "cards/renders/cbb-el-counter.mov" \
      -itsoffset 13.07 -i "cards/renders/cbb-el-chip-01.mov" \
      -itsoffset 16.87 -i "cards/renders/cbb-el-chip-02.mov" \
      -itsoffset 21.37 -i "cards/renders/cbb-el-chip-03.mov" \
      -itsoffset 25.07 -i "cards/renders/cbb-el-chip-04.mov" \
      -itsoffset 37.52 -i "cards/renders/cbb-el-chip-05.mov" \
      -itsoffset 44.07 -i "cards/renders/cbb-el-chip-06.mov" \
      -itsoffset 48.22 -i "cards/renders/cbb-el-chip-07.mov" \
      -itsoffset 50.52 -i "cards/renders/cbb-el-chip-08.mov" \
      -itsoffset 55.12 -i "cards/renders/cbb-el-chip-09.mov" \
      -itsoffset 58.32 -i "cards/renders/cbb-el-chip-10.mov" \
      -itsoffset 60.32 -i "cards/renders/cbb-el-chip-11.mov" \
      -itsoffset 65.37 -i "cards/renders/cbb-el-chip-12.mov" \
      -itsoffset 81.72 -i "cards/renders/cbb-el-chip-13.mov" \
      -itsoffset 90.02 -i "cards/renders/cbb-el-chip-14.mov" \
      -itsoffset 95.97 -i "cards/renders/cbb-el-chip-15.mov" \
      -itsoffset 98.02 -i "cards/renders/cbb-el-chip-16.mov" \
      -itsoffset 100.82 -i "cards/renders/cbb-el-chip-17.mov" \
      -itsoffset 104.28 -i "cards/renders/cbb-el-recap.mov" \
      -filter_complex "[0:v]tpad=stop_mode=add:stop_duration=6.7[base];
      [base][1:v]overlay=x=0:y=0:eof_action=pass:enable='between(t,12.9,104.38)'[v1];
      [v1][2:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,13.07,14.67)'[v2];
      [v2][3:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,16.87,18.47)'[v3];
      [v3][4:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,21.37,22.97)'[v4];
      [v4][5:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,25.07,28.17)'[v5];
      [v5][6:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,37.52,39.35)'[v6];
      [v6][7:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,44.07,45.67)'[v7];
      [v7][8:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,48.22,49.85)'[v8];
      [v8][9:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,50.52,52.12)'[v9];
      [v9][10:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,55.12,56.72)'[v10];
      [v10][11:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,58.32,59.92)'[v11];
      [v11][12:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,60.32,61.92)'[v12];
      [v12][13:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,65.37,66.97)'[v13];
      [v13][14:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,81.72,84.5)'[v14];
      [v14][15:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,90.02,91.62)'[v15];
      [v15][16:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,95.97,97.6)'[v16];
      [v16][17:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,98.02,100.1)'[v17];
      [v17][18:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,100.82,103.92)'[v18];
      [v18][19:v]overlay=x=480:y=1220:eof_action=pass:enable='between(t,104.28,110.98)'[v19];
      [v19]format=yuv420p[vout];
      [0:a]apad=pad_dur=6.7[aout]" \
      -map "[vout]" -map "[aout]" -t 30.00 \
      -c:v hevc_nvenc -preset p5 -rc vbr -cq 19 -b:v 0 -c:a aac -b:a 256k \
      "cards/renders/chromebball_test30.mp4"
    ;;
  review)
    ffmpeg -y -hide_banner -i "cards/sources/chromebball/ChromeBBall2425.mp4" \
      -itsoffset 12.9 -i "cards/renders/cbb-el-counter.mov" \
      -itsoffset 13.07 -i "cards/renders/cbb-el-chip-01.mov" \
      -itsoffset 16.87 -i "cards/renders/cbb-el-chip-02.mov" \
      -itsoffset 21.37 -i "cards/renders/cbb-el-chip-03.mov" \
      -itsoffset 25.07 -i "cards/renders/cbb-el-chip-04.mov" \
      -itsoffset 37.52 -i "cards/renders/cbb-el-chip-05.mov" \
      -itsoffset 44.07 -i "cards/renders/cbb-el-chip-06.mov" \
      -itsoffset 48.22 -i "cards/renders/cbb-el-chip-07.mov" \
      -itsoffset 50.52 -i "cards/renders/cbb-el-chip-08.mov" \
      -itsoffset 55.12 -i "cards/renders/cbb-el-chip-09.mov" \
      -itsoffset 58.32 -i "cards/renders/cbb-el-chip-10.mov" \
      -itsoffset 60.32 -i "cards/renders/cbb-el-chip-11.mov" \
      -itsoffset 65.37 -i "cards/renders/cbb-el-chip-12.mov" \
      -itsoffset 81.72 -i "cards/renders/cbb-el-chip-13.mov" \
      -itsoffset 90.02 -i "cards/renders/cbb-el-chip-14.mov" \
      -itsoffset 95.97 -i "cards/renders/cbb-el-chip-15.mov" \
      -itsoffset 98.02 -i "cards/renders/cbb-el-chip-16.mov" \
      -itsoffset 100.82 -i "cards/renders/cbb-el-chip-17.mov" \
      -itsoffset 104.28 -i "cards/renders/cbb-el-recap.mov" \
      -filter_complex "[0:v]tpad=stop_mode=add:stop_duration=6.7[base];
      [base][1:v]overlay=x=0:y=0:eof_action=pass:enable='between(t,12.9,104.38)'[v1];
      [v1][2:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,13.07,14.67)'[v2];
      [v2][3:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,16.87,18.47)'[v3];
      [v3][4:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,21.37,22.97)'[v4];
      [v4][5:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,25.07,28.17)'[v5];
      [v5][6:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,37.52,39.35)'[v6];
      [v6][7:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,44.07,45.67)'[v7];
      [v7][8:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,48.22,49.85)'[v8];
      [v8][9:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,50.52,52.12)'[v9];
      [v9][10:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,55.12,56.72)'[v10];
      [v10][11:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,58.32,59.92)'[v11];
      [v11][12:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,60.32,61.92)'[v12];
      [v12][13:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,65.37,66.97)'[v13];
      [v13][14:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,81.72,84.5)'[v14];
      [v14][15:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,90.02,91.62)'[v15];
      [v15][16:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,95.97,97.6)'[v16];
      [v16][17:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,98.02,100.1)'[v17];
      [v17][18:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,100.82,103.92)'[v18];
      [v18][19:v]overlay=x=480:y=1220:eof_action=pass:enable='between(t,104.28,110.98)'[v19];
      [v19]scale=1080:1920,format=yuv420p[vout];
      [0:a]apad=pad_dur=6.7[aout]" \
      -map "[vout]" -map "[aout]" -t 110.98 \
      -c:v h264_nvenc -preset p5 -rc vbr -cq 23 -b:v 0 -c:a aac -b:a 256k \
      "cards/renders/chromebball_review_1080.mp4"
    ;;
  final)
    ffmpeg -y -hide_banner -i "cards/sources/chromebball/ChromeBBall2425.mp4" \
      -itsoffset 12.9 -i "cards/renders/cbb-el-counter.mov" \
      -itsoffset 13.07 -i "cards/renders/cbb-el-chip-01.mov" \
      -itsoffset 16.87 -i "cards/renders/cbb-el-chip-02.mov" \
      -itsoffset 21.37 -i "cards/renders/cbb-el-chip-03.mov" \
      -itsoffset 25.07 -i "cards/renders/cbb-el-chip-04.mov" \
      -itsoffset 37.52 -i "cards/renders/cbb-el-chip-05.mov" \
      -itsoffset 44.07 -i "cards/renders/cbb-el-chip-06.mov" \
      -itsoffset 48.22 -i "cards/renders/cbb-el-chip-07.mov" \
      -itsoffset 50.52 -i "cards/renders/cbb-el-chip-08.mov" \
      -itsoffset 55.12 -i "cards/renders/cbb-el-chip-09.mov" \
      -itsoffset 58.32 -i "cards/renders/cbb-el-chip-10.mov" \
      -itsoffset 60.32 -i "cards/renders/cbb-el-chip-11.mov" \
      -itsoffset 65.37 -i "cards/renders/cbb-el-chip-12.mov" \
      -itsoffset 81.72 -i "cards/renders/cbb-el-chip-13.mov" \
      -itsoffset 90.02 -i "cards/renders/cbb-el-chip-14.mov" \
      -itsoffset 95.97 -i "cards/renders/cbb-el-chip-15.mov" \
      -itsoffset 98.02 -i "cards/renders/cbb-el-chip-16.mov" \
      -itsoffset 100.82 -i "cards/renders/cbb-el-chip-17.mov" \
      -itsoffset 104.28 -i "cards/renders/cbb-el-recap.mov" \
      -filter_complex "[0:v]tpad=stop_mode=add:stop_duration=6.7[base];
      [base][1:v]overlay=x=0:y=0:eof_action=pass:enable='between(t,12.9,104.38)'[v1];
      [v1][2:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,13.07,14.67)'[v2];
      [v2][3:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,16.87,18.47)'[v3];
      [v3][4:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,21.37,22.97)'[v4];
      [v4][5:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,25.07,28.17)'[v5];
      [v5][6:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,37.52,39.35)'[v6];
      [v6][7:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,44.07,45.67)'[v7];
      [v7][8:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,48.22,49.85)'[v8];
      [v8][9:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,50.52,52.12)'[v9];
      [v9][10:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,55.12,56.72)'[v10];
      [v10][11:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,58.32,59.92)'[v11];
      [v11][12:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,60.32,61.92)'[v12];
      [v12][13:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,65.37,66.97)'[v13];
      [v13][14:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,81.72,84.5)'[v14];
      [v14][15:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,90.02,91.62)'[v15];
      [v15][16:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,95.97,97.6)'[v16];
      [v16][17:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,98.02,100.1)'[v17];
      [v17][18:v]overlay=x=1360:y=0:eof_action=pass:enable='between(t,100.82,103.92)'[v18];
      [v18][19:v]overlay=x=480:y=1220:eof_action=pass:enable='between(t,104.28,110.98)'[v19];
      [v19]format=yuv420p[vout];
      [0:a]apad=pad_dur=6.7[aout]" \
      -map "[vout]" -map "[aout]" -t 110.98 \
      -c:v hevc_nvenc -preset p5 -rc vbr -cq 19 -b:v 0 -c:a aac -b:a 256k \
      "cards/renders/chromebball_final_4k60.mp4"
    ;;
  *) echo "unknown mode $MODE"; exit 1;;
esac
